GET http://localhost:4000/api/meme/getlist?page=1&limit=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmExYzIwNDQ2ZDFiMTExZDZhZGQ2YWUiLCJpYXQiOjE2MTU3NDE5NjgsImV4cCI6MTYxNTc0MTk4M30.UAk9O6lUoe2WmsxUxDCzrHRCgsqASM7Ul_4cIPKx02A


###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmExYzIwNDQ2ZDFiMTExZDZhZGQ2YWUiLCJpYXQiOjE2MTUyMDc3OTgsImV4cCI6MTYxNTIwNzgxM30.C1sknprfoyCdjBcIMGJ42-jRaC4VSUxsapxOl2bumdg"
}

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "5@gmail.com",
  "password": "123123"
}