env:  
  node: true  
extends:  
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended  
parser: '@typescript-eslint/parser'  
parserOptions:  
  ecmaVersion: 9
rules:
  '@typescript-eslint/no-var-requires': 0
plugins:  
 - '@typescript-eslint'