# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # Install client node_modules
      - name: Install client node_modules
        working-directory: ./client
        run: yarn install
      # Install server node_modules
      - name: Install server node_modules
        working-directory: ./server-nestjs
        run: yarn install
      # Run client tests
      - name: Run client tests
        working-directory: ./client
        run: yarn run test
      # Run server unit tests
      - name: Run server unit-tests
        working-directory: ./server-nestjs
        run: yarn run test
      # Run server e2e-tests tests
      - name: Run server e2e-tests
        working-directory: ./server-nestjs
        run: yarn run test:e2e
